# Generated by Django 2.2.6 on 2019-10-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='member'),
        ),
    ]
