# Generated by Django 2.2.6 on 2019-10-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_and_do_people_info.UserProfile')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_and_do_people_info.Ministry')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ministry',
            field=models.ManyToManyField(related_name='user_in_ministry', through='go_and_do_people_info.MinistryMember', to='go_and_do_people_info.Ministry'),
        ),
    ]
