# Generated by Django 2.2.6 on 2019-10-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0002_userprofile_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(default=1998, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='go_and_do_people_info.Address'),
            preserve_default=False,
        ),
    ]
