# Generated by Django 2.2.6 on 2019-10-14 03:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0002_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_member',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='district name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='street name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=9, null=True, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
