# Generated by Django 2.2.6 on 2019-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0003_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=13131231, max_length=1),
            preserve_default=False,
        ),
    ]
