# Generated by Django 2.2.6 on 2019-10-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0003_auto_20191014_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
