# Generated by Django 2.2.6 on 2019-10-14 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0005_ministry_ministrymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='country name')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='event name')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='datetime')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('venue', models.CharField(max_length=100, verbose_name='event venue')),
            ],
        ),
        migrations.RenameModel(
            old_name='MinistryMember',
            new_name='Volunteer',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('ticket_id', models.CharField(blank=True, max_length=255, verbose_name='ticket number')),
                ('purchase_date', models.DateTimeField(auto_now=True, verbose_name='purchase date')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('price', models.FloatField(default=0, verbose_name='title name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_and_do_people_info.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_and_do_people_info.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title name')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_and_do_people_info.Country')),
            ],
        ),
    ]
