# Generated by Django 2.2.6 on 2019-10-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_and_do_people_info', '0006_auto_20191014_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
    ]
